== Materials in CityGML

=== Overview

CityGML is an open standard, published by OGC, used for the storage and exchange of virtual 3D city models. CityGML allows the integration of urban geodata for use across a variety of applications, including urban and landscape planning; Urban Digital Twins for Smart Cities; the Metaverse; Building Information Modeling (<<BIM>>); mobile telecommunication; disaster management; 3D cadastre; tourism; vehicle & pedestrian navigation; autonomous driving and driving assistance; facility management; and energy, traffic, and environmental simulations. CityGML is useful for large areas and small regions, not just cities, and can represent real-world terrain and 3D objects at different Levels Of Detail (<<LOD, LOD>>) simultaneously.

=== Materials in CityGML

Referring specifically to materials, CityGML has standardized concepts to capture how surfaces of objects look like - their appearance. It has added support for various formats, including standards such as <<X3D>> and COLLADA. However, at the time of this writing, CityGML has not standardized any semantical classification of materials or associated attributions into its base model yet.

Nevertheless, a specific implementation of CityGML can capture material-related information by introducing it as application-specific attribution on top of base CityGML concepts. The following XML schema snippet shows the declaration of an extension of `WallSurface` in the underlying CityGML Building model with two custom string properties named `Material_Name` and `Material_Grade`.

.Sample CityGML Material attribution definitions
[source, xml]
<xsd:element
    name="Material_Name" 
    type="xsd:string" 
    substitutionGroup="bldg:_GenericApplicationPropertyOfWallSurface">
</xsd:element>
<xsd:element
    name="Material_Grade" 
    type="xsd:string" 
    substitutionGroup="bldg:_GenericApplicationPropertyOfWallSurface">
</xsd:element>

The following GML snippet shows `WallSurface` data containing `Material_Name` and `Material_Grade` values based on the application-specific Material attribution extensions depicted above.

.Sample CityGML data using the Material attribution extensions
[source, xml]
<bldg:Building 
    xmlns:bldg="http://www.opengis.net/citygml/building/2.0">
  <bldg:boundedBy>
    <bldg:WallSurface>
      ...
      <app:Material_Name>Concrete</app:Material_Name>
      <app:Material_Grade>Portland Cement Type III</app:Material_Grade>
      ...
    </bldg:WallSurface>
  </bldg:boundedBy>
</bldg:Building>