== Conclusion

This discussion paper aimed at highlighting the increasing need for richer material data that machines can understand, both in terms of semantical classification as well as attribution. This paper focused on the AECO industries, as these needs have risen as they have adopted state of the art advancements in information technologies, especially Digital Twin (<<DT, DT>>) applications and processes.

This paper also presented summaries of the current state of a few schema ecosystems with respect to materials. From the two international standards discussed, <<IFC, IFC>> ranked better at addressing most of these needs. It treats materials as a first-class concept that can be attributed. Some common specialized material-properties are standardized in its ecosystem. Furthermore, even though it has not standardized a classification of materials on its own, IFC allows implementors to capture them in parallel.

Still, the schema ecosystems led by software vendors that were discussed go beyond that. They aim at standardizing material semantics, classification and attribution on their ecosystems - a key goal that enables generic automation downstream. The <<BIS, BIS>> model focuses on the standardization of semantical classification and attribution of materials relevant in the AECO industries. Granta MI further inpires by showcasing additional functionality that can be built on top of a rich semantical model, including template-driven and attribution-based classifications.

On the other hand, the `3D Tiles` international standard was discussed as an example of a schema ecosystem that currently lacks standardization of material semantics and attribution. Other international standards, such as CityGML, would greatly benefit from a similar evolution.